name: ddns
version: "1.0.0"
summary: Cloudflare DDNS client
description: etc
grade: stable
confinement: strict

apps:
  ddns:
    command: run
    daemon: simple
    restart-condition: on-abnormal
    plugs: [network]
  check:
    command: ddns check

parts:
  latest-go:
    plugin: nil
    build-packages:
    - golang-go
    override-build: |
      curl https://gist.githubusercontent.com/nixberg/63130bbc35266a636a9a671ecae6b0b3/raw/fb7014d820f834e185aaa972c5ee22627b26b266/latest-go.sh | /bin/sh
    stage:
    - bin
    prime:
    - -*
  ddns:
    after: [latest-go] 
    plugin: nil
    source: .
    override-build: |
      env GOBIN=$SNAPCRAFT_PART_INSTALL/bin GO111MODULE=on go install
  run:
    plugin: dump
    source: bin
    organize:
      run: bin/run