name: ddns
base: core18
version: "1"
summary: Cloudflare DDNS client
description: etc
grade: stable
confinement: strict

apps:
  ddns:
    command: ddns.sh
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
  check:
    command: ddns check

parts:
  ddns:
    build-snaps:
      - go
    plugin: nil
    source: .
    override-build: |
      env GOBIN=$SNAPCRAFT_PART_INSTALL/bin go install
  launcher:
    plugin: dump
    source: snap/local/
    organize:
      "*": bin/
