name: ddns
version: "1.0.0"
summary: Cloudflare DDNS client
description: etc
grade: stable
confinement: strict

apps:
  ddns:
    command: run
    daemon: simple
    restart-condition: on-abnormal
    plugs: [network]
  check:
    command: ddns check

parts:
  ddns:
    build-snaps:
      - go
    plugin: nil
    source: .
    override-build: |
      env GOBIN=$SNAPCRAFT_PART_INSTALL/bin GO111MODULE=on CGO_ENABLED=0 go install
  run:
    plugin: dump
    source: bin
    organize:
      run: bin/run
