name: ddns
version: "1.0.0"
summary: Cloudflare DDNS client
description: etc
grade: stable
confinement: strict

apps:
  ddns:
    command: start
    daemon: simple
    restart-condition: on-abnormal
    plugs: [network]
  check:
    command: ddns check

parts:
  go:
    source-tag: go1.11
  ddns:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/nixberg/ddns
  start:
    source: .
    plugin: dump
    stage:
      - bin/start
