name: ddns
summary: Cloudflare DDNS client
description: Etc.
version: "2"

base: core20
grade: devel
confinement: strict
epoch: 2

apps:
  ddns:
    command: bin/ddns.sh
    daemon: oneshot
    timer: 00:00~24:00/720 # Every two minutes.
    plugs:
      - network

hooks:
  configure:
    plugs:
      - network

parts:
  ddns:
    plugin: go
    source: .

  launcher:
    plugin: dump
    source: snap/local/
    organize:
      "*": bin/
